LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := vega

MODULES += app/mt_boot \

MTK_EMMC_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LCM_PHYSICAL_ROTATION = 0
CONFIG_CUSTOM_LK_LCM="hx8369b_wvga_dsi_vdo_tinno"
#nt35590_hd720_dsi_cmd_auo = yes

BOOT_LOGO := wvga

MTK_SECURITY_SW_SUPPORT = no #yes
MTK_VERIFIED_BOOT_SUPPORT = no #yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
CUSTOM_SEC_AUTH_SUPPORT = no

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
